/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.AlunoDAO;
import dao.HistoricoPesoDAO;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Aluno;
import modelo.HistoricoPeso;



/**
 *
 * @author gusta
 */
public class HistoricoPesoGUI extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private final AlunoDAO alunoDAO;
    private HistoricoPesoDAO historicopesoDao;

    /**
     * Creates new form HistoricoPesoGUI
     */
    public HistoricoPesoGUI() {
        initComponents();
        model=(DefaultTableModel)jTable1.getModel();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        pack();
        setLocationRelativeTo(null); 
        setVisible(true);
    
        alunoDAO =new AlunoDAO();
        historicopesoDao= new HistoricoPesoDAO();
        
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        abrirDialogoPesquisaCPF();

    }
    
        private String formatarCPF(String cpf){
        String cpfApenasNumeros=cpf.replaceAll("[^0-9]","");
        if(cpfApenasNumeros.length()!=11){
            return "CPF Inválido";
        }
        
        return cpfApenasNumeros.substring(0,3)+"."+
               cpfApenasNumeros.substring(3,6)+"."+
               cpfApenasNumeros.substring(6,9)+"-"+
               cpfApenasNumeros.substring(9);
    }

    
        private double calcularIMC(double peso, double altura) {
        return peso / (altura * altura);
    }
        
        private String interpretarIMC(double imc){
            if(imc<18.5){
                return "Abaixo do Peso";
            }else if (imc >= 18.5 && imc< 24.9){
                return "Peso Normal";
            }else if (imc >= 24.9 && imc<29.9){
                return "Sobrepeso";
            }else{
                return "Obesidade";
            }
        }

        private void abrirDialogoPesquisaCPF() {
        String cpf = JOptionPane.showInputDialog("Digite o CPF do Aluno:");

        if (cpf != null && !cpf.isEmpty()) {
            cpf = formatarCPF(cpf);
            Aluno aluno = alunoDAO.consultar(cpf);

            if (aluno != null) {
                List<HistoricoPeso> historico = historicopesoDao.consultarPorAluno(cpf);
                model.setRowCount(0);

                for (HistoricoPeso registro : historico) {
                    double imc = calcularIMC(registro.getPeso(), registro.getaltura());
                    String interpretacaoIMC = interpretarIMC(imc);
                    DecimalFormat df = new DecimalFormat("0.0");
                    String imcFormatado = df.format(imc);
                    Date dataConvertida = Date.from(registro.getData().atStartOfDay(ZoneId.systemDefault()).toInstant());
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                    String dataFormatada = sdf.format(dataConvertida);
                    model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), registro.getaltura(), registro.getPeso(), imcFormatado, dataFormatada,interpretacaoIMC});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
            }
        }
    }

        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Histórico Peso");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Altura", "Peso", "IMC", "Data Cadastro", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setText("Pesquisar Aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Importar Histórico");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cpf=JOptionPane.showInputDialog("Digite o CPF do Aluno:");
        
        if(cpf != null && !cpf.isEmpty()){
            cpf = formatarCPF(cpf);
            Aluno aluno = alunoDAO.consultar(cpf);
            
        if (aluno != null) {
            List<HistoricoPeso> historico = historicopesoDao.consultarPorAluno(cpf);
             model.setRowCount(0); 

            
            for(int i = 0; i<historico.size();i++){
            HistoricoPeso registro=historico.get(i);
            double imc = calcularIMC(registro.getPeso(), registro.getaltura());
            String interpretacaoIMC = interpretarIMC(imc);
            DecimalFormat df = new DecimalFormat("0.0");
            String imcFormatado=df.format(imc);
            Date dataConvertida = Date.from(registro.getData().atStartOfDay(ZoneId.systemDefault()).toInstant());
            SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = sdf.format(dataConvertida);
            model.addRow(new Object[]{aluno.getCpf(), aluno.getNome(), registro.getaltura(), registro.getPeso(),imcFormatado,dataFormatada,interpretacaoIMC});
        } }else {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
                }
        }
        
    

    

        
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    String nomeArquivoBase = "Histórico de Peso de %s %d.txt"; 
    String diretorio = ".";
    
    String nomeAluno = jTable1.getValueAt(0,1).toString().replaceAll("[^a-zA-Z0-9]", "");
    int numeroArquivo = 1;
    File arquivo;
    do {
        String nomeArquivo = String.format(nomeArquivoBase, nomeAluno, numeroArquivo);
        arquivo = new File(diretorio, nomeArquivo);
        numeroArquivo++;
    } while (arquivo.exists());
    
    
    
     try (FileWriter fw = new FileWriter(arquivo);
                BufferedWriter bw = new BufferedWriter(fw)) {

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String cpf = (String) jTable1.getValueAt(i, 0);
            String nome = (String) jTable1.getValueAt(i, 1);
            double altura = (double) jTable1.getValueAt(i,2);
            double peso = (double) jTable1.getValueAt(i, 3);
            String dataCalculo = (String) jTable1.getValueAt(i, 5);
            String imc = (String) jTable1.getValueAt(i, 4);
            String resultado = (String) jTable1.getValueAt(i, 6);
            

           
                
              
            
            String linha = String.format("CPF: %s | Nome: %s | Altura: %.2f| Peso: %.2f| IMC:  %s| Data de Cadastro:  %s| Interpretação: %s%n",cpf, nome, altura , peso , imc,dataCalculo, resultado);
             
            bw.write(linha);
        }
                JOptionPane.showMessageDialog(this, "Histórico importado para o arquivo: " + nomeAluno);
            
    }   catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao tentar gravar o histórico: " + ex.getMessage());

    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoPesoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoPesoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoPesoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoPesoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoPesoGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
